language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: XKc3BTVA/9sq4kDQ1wcQH4Skb3g+X5d5tmgKbj01R49pt2FhBwOX0aMJvr5ug5uyEGw2oX50ff8jA9/ocQVdfLlvUfNmSym8vHER6Q3/DtaBmDzWPLP7DFRT3/6taLMEJrjJKqQwXL68l7UAqZtHUAX1d2JC0FkTcMB8FmSVuJw=
  on:
    tags: true
    repo: noflo/noflo-s3
